---
## configs for mimic-iv-core

data_linkage:
    ed: True # link mimic-iv-ED dataset
    hosp: True
    icu: True

category_to_numeric:
    insurance: { Medicare: 1, Medicaid: 2, Other: 0, Default: 0}
    language: {ENGLISH: 1, Default: 0}
    marital_status: {WIDOWED: 1, SINGLE: 2, MARRIED: 3, DIVORCED: 4, Default: 0}
    race:
        ASIAN: 8
        ASIAN - ASIAN INDIAN: 20
        ASIAN - CHINESE: 9
        ASIAN - SOUTH EAST ASIAN: 18
        BLACK/AFRICAN: 14
        BLACK/AFRICAN AMERICAN: 2
        BLACK/CAPE VERDEAN: 11
        BLACK/CARIBBEAN ISLAND: 13
        Default: 0
        HISPANIC OR LATINO: 7
        HISPANIC/LATINO - DOMINICAN: 12
        HISPANIC/LATINO - GUATEMALAN: 19
        HISPANIC/LATINO - PUERTO RICAN: 5
        OTHER: 3
        PATIENT DECLINED TO ANSWER: 15
        PORTUGUESE: 17
        UNABLE TO OBTAIN: 16
        UNKNOWN: 4
        WHITE: 1
        WHITE - EASTERN EUROPEAN: 21
        WHITE - OTHER EUROPEAN: 6
        WHITE - RUSSIAN: 10
    careunit:
        Cardiac Surgery: 17
        Cardiac Vascular Intensive Care Unit (CVICU): 20
        Coronary Care Unit (CCU): 26
        Default: 0
        Discharge Lounge: 5
        Emergency Department: 1
        Emergency Department Observation: 4
        Hematology/Oncology: 9
        Hematology/Oncology Intermediate: 25
        Labor & Delivery: 15
        Med/Surg: 6
        Med/Surg/GYN: 12
        Med/Surg/Trauma: 13
        Medical Intensive Care Unit (MICU): 16
        Medical/Surgical (Gynecology): 27
        Medical/Surgical Intensive Care Unit (MICU/SICU): 19
        Medicine: 3
        Medicine/Cardiology: 7
        Neurology: 8
        Obstetrics (Postpartum & Antepartum): 21
        PACU: 14
        Psychiatry: 23
        Surgery: 28
        Surgery/Pancreatic/Biliary/Bariatric: 29
        Surgery/Trauma: 18
        Surgical Intensive Care Unit (SICU): 22
        Transplant: 11
        Trauma SICU (TSICU): 24
        Vascular: 10
        empty: 2
    

remove_rule:
    pass1:
        duration_minmax: [4, 96]
    pass2:
        # gradually eliminate invalid cols/rows in several iterations
        # the last value in each list is an approximation of final missrate threshold
        max_col_missrate: [0.95, 0.95, 0.95]
        max_subject_missrate: [0.95, 0.9, 0.8]
        adm_select_strategy: default # default always select the first available admission. Another option: random

generate_table:
    align_target: [] # no target: pipeline will use the start time of nearest valid feature
    default_missing_value: -1
    calculate_bin: avg # how to calculate multiple data points in a discrete bin: avg=use average value, latest: use last value
    delta_t_hour: 1.0

k-fold: 5
validation_proportion: 0.15 # use X*80% samples for validation
compress_cache: True # compress cache file to speed up loading, it will slow down cache dumping
compress_suffix: .gz # zip: fast compression but slow loading. xz: slow compression but fast loading (smaller file size)


version:
    vent@origin:
        fill_missvalue: none
        feature_limit: []
        forbidden_feas: [
            Weight, BMI, Height (Inches), Weight (Lbs), dod,
            ventilation_start, ventilation_end, ventilation_num, hosp_expire
        ]
    vent@filled:
        fill_missvalue: avg
        feature_limit: []
        forbidden_feas: [
            Weight, BMI, Height (Inches), Weight (Lbs), dod,
            ventilation_start, ventilation_end, ventilation_num, hosp_expire
        ]

value_clip: {}

## configs for mimic-iv-vent

# 0: no ventilation, 1: non-invasive, 2:invasive
ventilation_to_numeric: {
    SupplementalOxygen: 1,
    HFNC: 1,
    NonInvasiveVent: 1,
    InvasiveVent: 2,
    Tracheostomy: 2
}
    
    