---
## configs for mimic-iv-core

data_linkage:
    ed: True # link mimic-iv-ED dataset
    hosp: True
    icu: True

category_to_numeric:
    insurance: { Medicare: 1, Medicaid: 2, Other: 0, Default: 0}
    language: {ENGLISH: 1, Default: 0}
    marital_status: {WIDOWED: 1, SINGLE: 2, MARRIED: 3, DIVORCED: 4, Default: 0}
    race: {WHITE: 1, Default: 0}
    careunit: {'Emergency Department': 1, 'Medicine': 2, 'Emergency Department Observation': 3, 'Default': 0}
    
remove_rule:
    pass1:
        duration_minmax: [2, 192]
    pass2:
        # gradually eliminate invalid cols/rows in several iterations
        # the last value in each list is an approximation of final missrate threshold
        max_col_missrate: [0.99] # there are >5000 features. They will cause OOM
        max_subject_missrate: [1.0]
        adm_select_strategy: default # default always select zero. Another option: random

generate_table:
    align_target: []
    default_missing_value: -1
    calculate_bin: avg # how to calculate multiple data points in a discrete bin: avg=use average value, latest: use last value
    delta_t_hour: 4.0

k-fold: 5
validation_proportion: 0.15 # use 0.15*80% samples for validation
compress_cache: True # compress cache file to speed up loading 
compress_suffix: .gz # zip: fast compression but slow loading. xz: slow compression but fast loading (smaller file size)

version:
    raw@version:
        fill_missvalue: none # do not fill miss value in feature explore status
        feature_limit: []
        forbidden_feas: []

value_clip: {}

