---
data_linkage:
  ed: True # link mimic-iv-ED dataset
  hosp: True
  icu: True
category_to_numeric:
  insurance: { Medicare: 1, Medicaid: 2, Other: 0, Default: 0}
  language: {ENGLISH: 1, Default: 0}
  marital_status: {WIDOWED: 1, SINGLE: 2, MARRIED: 3, DIVORCED: 4, Default: 0}
  race: {WHITE: 1, Default: 0}
  careunit: {'Emergency Department': 1, 'Medicine': 2, 'Emergency Department Observation': 3, 'Default': 0}
miss_dict_reference:
  PF_ratio: ['220224', '223835']
  PPD:
    - '220050'
    - '220051'
  MAP:
    - '220050'
    - '220051'
  shock_index:
    - '220050'
    - '220045'
  systolic pressure:
    - Blood Pressure
  diastolic pressure:
    - Blood Pressure
remove_rule:
  pass1:
    target_id: ['220224', '223835']
    duration_minmax: [2, 96]
    check_sepsis_time: [-30, 10]
  pass2:
    # gradually eliminate invalid cols/rows in several iterations
    # the last value in each list is an approximation of final missrate threshold
    max_col_missrate: [0.9, 0.8, 0.5]
    max_subject_missrate: [0.9, 0.8, 0.5]
    adm_select_strategy: default # default always select zero. Another option: random
generate_table:
  align_target: ['220224', '223835']
  default_missing_value: -1
  delta_t_hour: 0.5
k-fold: 5
validation_proportion: 0.15 # use 0.15*80% samples for validation
compress_cache: True # compress cache file to speed up loading 
version:
  explore_version:
    fill_missvalue: none # do not fill miss value in feature explore status
    feature_limit: []
    forbidden_feas: []
  original_version:
    fill_missvalue: avg
    feature_limit: []
    forbidden_feas: [Weight, BMI, Height (Inches), '225677', '220545', '226730', '226531', Weight (Lbs), '227467', '220339', '227443', '220587', 'dod']
value_clip:
  Inspired O2 Fraction:
    min: 21
    max: 100
  Arterial O2 pressure:
    min: 0
    max: 500
